version: '3.8'
services:
  friday:
    image: wechaty/friday:latest
    labels:
      - com.centurylinklabs.watchtower.enable=true
    init: true
    env_file: .env
    expose:
      - 80
    container_name: friday
    network_mode: bridge
    volumes:
      - .wechaty:/bot/.wechaty
      - data:/bot/data
    environment:
      - WEB_PORT=80
      - VIRTUAL_HOST=friday.chatie.io
      - LETSENCRYPT_HOST=friday.chatie.io
      - HTTPS_METHOD=noredirect
    healthcheck:
      test: ["CMD", "true"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
volumes:
  .wechaty:
  data:
